---

  - block:

    - name: UWSGI | install dependencies
      apt: name="{{item}}" state="present"
      with_items:
        - libssl-dev
      tags:
        - uwsgi

    when: ansible_os_family == "Debian"



  - name: UWSGI | pip install UWSGI
    pip: name=uwsgi executable="{{uwsgi_pip | default(omit)}}"
    tags:
      - uwsgi

  - name: UWSGI | Create configuration directories
    file: path="{{item}}" state=directory
    with_items:
      - "/etc/uwsgi/apps-available"
      - "/etc/uwsgi/apps-enabled"
      - "/etc/uwsgi/vassals"
    tags:
      - uwsgi
