---

  - include: project_appuser_create.yml

  - include: project_deploy_app.yml

  - include: project_virtualenv_create.yml

  - include: project_tools_create.yml

#  - include: project_syncdb.yml

  - include: project_collect_static.yml

  - include: create_uwsgi_vassal.yml

# Not needed for docker
#  - include: "{{role_dir}}/components/create_nginx_conf_uwsgi.yml"

